import type { Metadata } from 'next'
import { Geist, Geist_Mono, Inter, Outfit } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'

const outfitHeading = Outfit({ subsets: ['latin'], variable: '--font-heading' })

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang='en'
      className={cn(
        'h-full',
        'antialiased',
        'font-sans',
        inter.variable,
        outfitHeading.variable,
      )}>
      <body className='min-h-full flex flex-col'>{children}</body>
    </html>
  )
}
